$(function(){
	selectLocation();
	selectMonth();
	loadMonth();
	loadChinaMap();
	chinaIncreChart();
	personFigure();
	personIcre();
	keyArea();
	requestKeyArea();
	requestChinaMap();
	requestPersonData();
});
